
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package CupYFlex.Listas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEDER = 12;
  public static final int DOSPUNTOS = 18;
  public static final int CADENA = 15;
  public static final int BOOLT = 8;
  public static final int COMA = 19;
  public static final int LLAVECIERRA = 14;
  public static final int NOMBRE = 3;
  public static final int EOF = 0;
  public static final int BOOLF = 7;
  public static final int CIRCULAR = 5;
  public static final int DIV = 17;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 16;
  public static final int PARABRE = 9;
  public static final int PARCIERRA = 10;
  public static final int PISTAS = 4;
  public static final int LISTA = 2;
  public static final int CORCHETEIZ = 11;
  public static final int ALEATORIA = 6;
  public static final int LLAVEABRE = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LISTA",
  "NOMBRE",
  "PISTAS",
  "CIRCULAR",
  "ALEATORIA",
  "BOOLF",
  "BOOLT",
  "PARABRE",
  "PARCIERRA",
  "CORCHETEIZ",
  "CORCHETEDER",
  "LLAVEABRE",
  "LLAVECIERRA",
  "CADENA",
  "IDENTIFICADOR",
  "DIV",
  "DOSPUNTOS",
  "COMA"
  };
}

