
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package CupYFlex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 46;
  public static final int SUMASUMA = 51;
  public static final int CONTINUAR = 22;
  public static final int CORCHETEDER = 42;
  public static final int MENSAJE = 30;
  public static final int MAYOR = 60;
  public static final int KEEP = 12;
  public static final int POT = 58;
  public static final int PRIMOS = 35;
  public static final int PISTA = 9;
  public static final int LONGITUD = 29;
  public static final int NOT = 71;
  public static final int SBOOLEAN = 5;
  public static final int NOR = 69;
  public static final int ORDENAR = 27;
  public static final int VAR = 13;
  public static final int BOOLT = 11;
  public static final int IMPARES = 34;
  public static final int SALIR = 18;
  public static final int HACER = 21;
  public static final int PARA = 19;
  public static final int SDOBLE = 4;
  public static final int PARES = 33;
  public static final int COMA = 73;
  public static final int PARABRE = 39;
  public static final int BOOLF = 10;
  public static final int ENTERO = 48;
  public static final int MODULO = 57;
  public static final int PARCIERRA = 40;
  public static final int IGUAL = 65;
  public static final int DECIMAL = 47;
  public static final int CHAR = 49;
  public static final int DOSPUNTOS = 2;
  public static final int PUNTOYCOMA = 72;
  public static final int ASTERISCO = 54;
  public static final int SWITCH = 15;
  public static final int SENTERO = 3;
  public static final int VOID = 23;
  public static final int DIV = 56;
  public static final int ELSE = 38;
  public static final int MENOS = 55;
  public static final int MENOR = 61;
  public static final int MAS = 53;
  public static final int SCARACTER = 6;
  public static final int ARREGLO = 14;
  public static final int EOF = 0;
  public static final int MIENTRAS = 20;
  public static final int DEFAULT = 16;
  public static final int SUMARIZAR = 28;
  public static final int MENORIGUAL = 63;
  public static final int PRINCIPAL = 24;
  public static final int CORCHETEIZ = 41;
  public static final int OR = 68;
  public static final int error = 1;
  public static final int REPRODUCIR = 25;
  public static final int MASIGUAL = 50;
  public static final int IF = 37;
  public static final int ESNULO = 64;
  public static final int EXTIENDE = 8;
  public static final int UMENOS = 74;
  public static final int CASO = 17;
  public static final int ESPERAR = 26;
  public static final int LLAVECIERRA = 44;
  public static final int RETORNA = 36;
  public static final int NOIGUAL = 59;
  public static final int CADENA = 45;
  public static final int MAYORIGUAL = 62;
  public static final int LLAVEABRE = 43;
  public static final int ASCENDENTE = 31;
  public static final int AND = 66;
  public static final int DESCENDENTE = 32;
  public static final int MENOSMENOS = 52;
  public static final int NAND = 67;
  public static final int XOR = 70;
  public static final int SCADENA = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUNTOS",
  "SENTERO",
  "SDOBLE",
  "SBOOLEAN",
  "SCARACTER",
  "SCADENA",
  "EXTIENDE",
  "PISTA",
  "BOOLF",
  "BOOLT",
  "KEEP",
  "VAR",
  "ARREGLO",
  "SWITCH",
  "DEFAULT",
  "CASO",
  "SALIR",
  "PARA",
  "MIENTRAS",
  "HACER",
  "CONTINUAR",
  "VOID",
  "PRINCIPAL",
  "REPRODUCIR",
  "ESPERAR",
  "ORDENAR",
  "SUMARIZAR",
  "LONGITUD",
  "MENSAJE",
  "ASCENDENTE",
  "DESCENDENTE",
  "PARES",
  "IMPARES",
  "PRIMOS",
  "RETORNA",
  "IF",
  "ELSE",
  "PARABRE",
  "PARCIERRA",
  "CORCHETEIZ",
  "CORCHETEDER",
  "LLAVEABRE",
  "LLAVECIERRA",
  "CADENA",
  "IDENTIFICADOR",
  "DECIMAL",
  "ENTERO",
  "CHAR",
  "MASIGUAL",
  "SUMASUMA",
  "MENOSMENOS",
  "MAS",
  "ASTERISCO",
  "MENOS",
  "DIV",
  "MODULO",
  "POT",
  "NOIGUAL",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "ESNULO",
  "IGUAL",
  "AND",
  "NAND",
  "OR",
  "NOR",
  "XOR",
  "NOT",
  "PUNTOYCOMA",
  "COMA",
  "UMENOS"
  };
}

