/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Compilador.Entorno;
import Backend.Compilador.ManejadorArchivo;
import Backend.Compilador.Simbolo;
import Backend.Instrucciones.Asignacion;
import Backend.Instrucciones.Declaracion;
import Backend.Instrucciones.Funcion;
import Backend.Instrucciones.Metodo;
import Backend.Instrucciones.PistaInst;
import Backend.Interfaces.Instruccion;
import Backend.LectorArchivo;
import Backend.Listas.Lista;
import Backend.Reproductor.Pista;
import CupYFlex.AnalizadorLexico;
import CupYFlex.ErrorS;
import CupYFlex.Listas.AnalizadorLexicoList;
import CupYFlex.Listas.ErrorL;
import CupYFlex.Listas.parserL;
import CupYFlex.parser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author astridmc
 */
public class Principal extends javax.swing.JFrame {
     boolean editor = false;
    ArrayList<String> formatos = new ArrayList();
    ArrayList<String> formatos2 = new ArrayList();
    ArrayList<Editor> documentos = new ArrayList();
    ArrayList<Editor> documentos2 = new ArrayList();

    private DefaultTreeModel modelo;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        diseño();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        panelArchivos = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consola2 = new javax.swing.JTextArea();
        panelArchivos2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaRep = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        menuBarra = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnNuevo = new javax.swing.JMenuItem();
        btnAbrir = new javax.swing.JMenuItem();
        btnGuardar = new javax.swing.JMenuItem();
        btnGuardarComo = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnNuevoLista = new javax.swing.JMenuItem();
        btnRep = new javax.swing.JMenu();
        btnAnalizar = new javax.swing.JMenuItem();
        limpiarConsola = new javax.swing.JMenuItem();
        btnErrores = new javax.swing.JMenuItem();
        btnAnalizarLista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 9, 9));

        jTabbedPane1.setBackground(new java.awt.Color(213, 213, 213));

        consola.setBackground(new java.awt.Color(1, 1, 1));
        consola.setColumns(20);
        consola.setForeground(new java.awt.Color(254, 254, 254));
        consola.setRows(5);
        jScrollPane1.setViewportView(consola);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelArchivos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editor Pista", jPanel4);

        consola2.setBackground(new java.awt.Color(1, 1, 1));
        consola2.setColumns(20);
        consola2.setForeground(new java.awt.Color(254, 254, 254));
        consola2.setRows(5);
        jScrollPane2.setViewportView(consola2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelArchivos2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelArchivos2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editor Lista", jPanel5);

        jLabel3.setText("LISTAS DE REPRODUCCION");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Listas");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Lista1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pista1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pista2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pista3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pista4");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Lista3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pista4");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pista6");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pista7");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        listaRep.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(listaRep);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3))
                    .addComponent(jLabel3))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Biblioteca", jPanel3);

        jPanel2.setBackground(new java.awt.Color(1, 1, 1));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(104, 232, 199)));

        panel1.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jProgressBar1.setBackground(new java.awt.Color(104, 253, 185));

        jLabel1.setFont(new java.awt.Font("Sahadeva", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(201, 243, 229));
        jLabel1.setText("3:30");

        jLabel2.setFont(new java.awt.Font("Sahadeva", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 243, 229));
        jLabel2.setText("Nombre ");

        btnPlay.setBackground(new java.awt.Color(1, 1, 1));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/playP.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnPausa.setBackground(new java.awt.Color(1, 1, 1));
        btnPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/stopP.png"))); // NOI18N
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });

        btnDetener.setBackground(new java.awt.Color(1, 1, 1));
        btnDetener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/pausaP.png"))); // NOI18N
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnDetener, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(btnDetener, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );

        menuBarra.setBackground(new java.awt.Color(188, 228, 230));
        menuBarra.setForeground(new java.awt.Color(255, 0, 0));
        menuBarra.setFont(new java.awt.Font("URW Bookman L", 1, 18)); // NOI18N
        menuBarra.setPreferredSize(new java.awt.Dimension(118, 40));

        jMenu3.setBackground(new java.awt.Color(77, 183, 175));
        jMenu3.setForeground(new java.awt.Color(1, 1, 1));
        jMenu3.setText(" Archivo ");
        jMenu3.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N

        btnNuevo.setBackground(new java.awt.Color(185, 240, 234));
        btnNuevo.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jMenu3.add(btnNuevo);

        btnAbrir.setBackground(new java.awt.Color(143, 235, 220));
        btnAbrir.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jMenu3.add(btnAbrir);

        btnGuardar.setBackground(new java.awt.Color(185, 240, 234));
        btnGuardar.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jMenu3.add(btnGuardar);

        btnGuardarComo.setBackground(new java.awt.Color(143, 235, 220));
        btnGuardarComo.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnGuardarComo.setText("Guardar Como");
        btnGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarComoActionPerformed(evt);
            }
        });
        jMenu3.add(btnGuardarComo);

        btnSalir.setBackground(new java.awt.Color(185, 240, 234));
        btnSalir.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu3.add(btnSalir);

        btnNuevoLista.setBackground(new java.awt.Color(185, 240, 234));
        btnNuevoLista.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnNuevoLista.setText("Nuevo Lista");
        btnNuevoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoListaActionPerformed(evt);
            }
        });
        jMenu3.add(btnNuevoLista);

        menuBarra.add(jMenu3);

        btnRep.setBackground(new java.awt.Color(77, 183, 175));
        btnRep.setForeground(new java.awt.Color(1, 1, 1));
        btnRep.setText("Acciones");
        btnRep.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N

        btnAnalizar.setBackground(new java.awt.Color(185, 240, 234));
        btnAnalizar.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        btnRep.add(btnAnalizar);

        limpiarConsola.setBackground(new java.awt.Color(143, 235, 220));
        limpiarConsola.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        limpiarConsola.setText("LimpiarConsola");
        limpiarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarConsolaActionPerformed(evt);
            }
        });
        btnRep.add(limpiarConsola);

        btnErrores.setBackground(new java.awt.Color(185, 240, 234));
        btnErrores.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnErrores.setText("Ver Errores");
        btnErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErroresActionPerformed(evt);
            }
        });
        btnRep.add(btnErrores);

        btnAnalizarLista.setBackground(new java.awt.Color(185, 240, 234));
        btnAnalizarLista.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnAnalizarLista.setText("Analizar Lista");
        btnAnalizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarListaActionPerformed(evt);
            }
        });
        btnRep.add(btnAnalizarLista);

        menuBarra.add(btnRep);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPausaActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
         ErrorS.tablaErrores.clear();
        NombrarDialog nombrar = new NombrarDialog(this);
        nombrar.setVisible(true);

        String nombre = nombrar.getNombre();
        
        verificarExistenciaTab(nombre, null);
        formatos.add(nombre);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        ErrorS.tablaErrores.clear();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        System.out.println("entrandi archivo");
        //FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("TEXT FILES", "len");
        //fileChooser.setFileFilter(imgFilter);
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.CANCEL_OPTION) {
            File fileName = fileChooser.getSelectedFile();
            if ((fileName == null) || (fileName.getName().equals(""))) {
            } else {
                try {
                    verificarExistenciaTab(fileName.getName(), fileName);
                    formatos.add(fileName.getName());
                } catch (Exception e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, "Error cargando Archivo");
                }
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        int indice = panelArchivos.getSelectedIndex();
        if (documentos.get(indice).getDocumento() == null) {
            NombrarDialog nombrar = new NombrarDialog(this);
            nombrar.setVisible(true);
            String nombre = nombrar.getNombre();
            JFileChooser chooser = new JFileChooser();
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int result = chooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                ManejadorArchivo.GuardarArchivo(chooser.getSelectedFile().getAbsolutePath() + ".text" , documentos.get(indice).ObtenerTexto());
            }
        } else {
            String texto = documentos.get(indice).ObtenerTexto();
            File archivo = documentos.get(indice
            ).getDocumento();
            LectorArchivo lector = new LectorArchivo();
            lector.GuardarTexto(archivo, texto);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarComoActionPerformed
        NombrarDialog nombrar = new NombrarDialog(this);
        nombrar.setVisible(true);

        int indice = panelArchivos.getSelectedIndex();
        String nombre = nombrar.getNombre();
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            ManejadorArchivo.GuardarArchivo(chooser.getSelectedFile().getAbsolutePath() + ".text", documentos.get(indice).ObtenerTexto());
        }
    }//GEN-LAST:event_btnGuardarComoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         ErrorS.tablaErrores.clear();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        
        try {           
                 ErrorS.tablaErrores.clear();
                consola.setText("");
                int indice = panelArchivos.getSelectedIndex();
                AnalizadorLexico lex = new AnalizadorLexico(new BufferedReader( new StringReader(documentos.get(indice).ObtenerTexto())));
                lex.pintar.darEstilo(documentos.get(indice).ObtenerTexto());
                documentos.get(indice).AreaTexto.setDocument(lex.pintar.caja2.getDocument());
                parser  sint=new parser(lex);
                System.out.println(documentos.get(indice).ObtenerTexto());
                //aca se compila                   
                sint.parse();
                PistaInst pist =sint.getInstruccion();
                Entorno global = new Entorno(null);
                try{
                    Pista pista= new Pista(pist.getNombre());
                    ArrayList<Instruccion> ins = pist.getInstrucciones();
                    for (Instruccion in : ins) {
                        Entorno entornoObjeto = new Entorno(null);
                        if("funcion".equals(in.tipoIns())){
                            Funcion fun = (Funcion)in;
                            Simbolo sim = new Simbolo( fun.getIdentificador(), fun.getTipo());
                        }else if("metodo".equals(in.tipoIns())){
                            Metodo fun = (Metodo)in;
                            Simbolo sim = new Simbolo( fun.getIdentificador(), fun.getTipo());
                        }else if("asignacion".equals(in.tipoIns())){
                            Asignacion fun = (Asignacion)in;
                        }else{
                            Declaracion  fun = (Declaracion )in;
                            for (int i = 0; i < fun.getIds().size(); i++) {
                                Simbolo sim = new Simbolo( fun.getIds().get(i), fun.getTipo());
                            }
                        }

                    }
                    consola.setText(consola.getText()+"\nAVISO: Analisis realizado correctamente.");
                    for (int i = 0; i < sint.avisos.size(); i++) {
                        consola.setText(consola.getText()+"\n"+sint.avisos.get(i));
                    }
                    jTabbedPane1.setSelectedIndex(1);
                } catch(NullPointerException n){
                    
                }
            } catch (Exception ex) {
                 Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                 consola.setText(consola.getText()+"\nError: No se pudo realizar el analisis sintactico.");
            }
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void limpiarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarConsolaActionPerformed
        consola.setText("");
    }//GEN-LAST:event_limpiarConsolaActionPerformed

    private void btnErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErroresActionPerformed
        Errores tablaErrores = new Errores(this,true, ErrorS.tablaErrores);
        tablaErrores.setVisible(true);
    }//GEN-LAST:event_btnErroresActionPerformed

    private void btnNuevoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoListaActionPerformed
        ErrorS.tablaErrores.clear();
        NombrarDialog nombrar = new NombrarDialog(this);
        nombrar.setVisible(true);

        String nombre = nombrar.getNombre();
        
        verificarExistenciaTab2(nombre, null);
        formatos2.add(nombre);
    }//GEN-LAST:event_btnNuevoListaActionPerformed

    private void btnAnalizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarListaActionPerformed
        
        try {                     
                   ErrorL.tablaErrores.clear();
                consola2.setText("");
                int indice = panelArchivos2.getSelectedIndex();
                AnalizadorLexicoList lex = new AnalizadorLexicoList(new BufferedReader( new StringReader(documentos2.get(indice).ObtenerTexto())));
                lex.pintar.darEstilo(documentos2.get(indice).ObtenerTexto());
                documentos2.get(indice).AreaTexto.setDocument(lex.pintar.caja2.getDocument());
                parserL  sint=new parserL(lex);
                System.out.println(documentos2.get(indice).ObtenerTexto());
                //aca se compila                   
                sint.parse();
                ArrayList<Lista> listas =sint.listas;
                Entorno global = new Entorno(null);
                try{
                    DefaultMutableTreeNode padre = new DefaultMutableTreeNode("listas"); 
                    modelo= new DefaultTreeModel(padre);
                  listaRep.setModel(modelo);
                    for (Lista in : listas) {
                     DefaultMutableTreeNode  hijo =new DefaultMutableTreeNode(in.getNombre());
                    modelo.insertNodeInto(hijo, padre, padre.getChildCount());
                        for (int i = 0; i < in.getPistasNombres().size(); i++) {
                            DefaultMutableTreeNode  hij=new DefaultMutableTreeNode(in.getPistasNombres().get(i));
                            modelo.insertNodeInto(hij, hijo, hijo.getChildCount());
                        }
                    
                    }
                    consola2.setText(consola2.getText()+"\nAVISO: Analisis realizado correctamente.");
                    for (int i = 0; i < sint.avisos.size(); i++) {
                        consola2.setText(consola2.getText()+"\n"+sint.avisos.get(i));
                    }
                    jTabbedPane1.setSelectedIndex(2);
                } catch(NullPointerException n){
                    
                }
            } catch (Exception ex) {
                 Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                 consola2.setText(consola2.getText()+"\nError: No se pudo realizar el analisis sintactico.");
            }
                        
    }//GEN-LAST:event_btnAnalizarListaActionPerformed
   

JLabel imagen = new JLabel();

    void diseño() {
        setTitle("CREADOR MUSICA");
        setLocation(200, 100);
        setIconImage(new ImageIcon("img3.png").getImage());

    }

    public void verificarExistenciaTab(String nombre, File doc) {
        boolean aux = false;
        int i = 0;
        for (i = 0; i < formatos.size(); i++) {
            if (nombre.equals(formatos.get(i))) {
                aux = true;
                break;
            } else {
                aux = false;
            }
        }
        if (aux) {
            JOptionPane.showMessageDialog(rootPane, "ya tiene un documento con ese mismo nombre");
        } else if (!aux) {
            Editor editor;
            LectorArchivo lector = new LectorArchivo();
            if (doc != null) {
                editor = new Editor(lector.IdentificarDatos(doc.getAbsolutePath()));
            } else {
                editor = new Editor("");
            }
            editor.setDocumento(doc);
            documentos.add(editor);
            panelArchivos.addTab(nombre, editor);
            int index = panelArchivos.indexOfTab(nombre);
            panelArchivos.setTabComponentAt(index, createTabHead(nombre));
        }
    }
    
    public void verificarExistenciaTab2(String nombre, File doc) {
        boolean aux = false;
        int i = 0;
        for (i = 0; i < formatos2.size(); i++) {
            if (nombre.equals(formatos2.get(i))) {
                aux = true;
                break;
            } else {
                aux = false;
            }
        }
        if (aux) {
            JOptionPane.showMessageDialog(rootPane, "ya tiene un documento con ese mismo nombre");
        } else if (!aux) {
            Editor editor;
            LectorArchivo lector = new LectorArchivo();
            if (doc != null) {
                editor = new Editor(lector.IdentificarDatos(doc.getAbsolutePath()));
            } else {
                editor = new Editor("");
            }
            editor.setDocumento(doc);
            documentos2.add(editor);
            panelArchivos2.addTab(nombre, editor);
            int index = panelArchivos2.indexOfTab(nombre);
            panelArchivos2.setTabComponentAt(index, createTabHead(nombre));
        }
    }
    

    public JPanel createTabHead(String title) {
        JPanel pnlTab = new JPanel();
        pnlTab.setLayout(new BoxLayout(pnlTab, BoxLayout.LINE_AXIS));
        pnlTab.setOpaque(false);
        JButton btnClose = new JButton("x");
        JLabel lblTitle = new JLabel(title + "    ");
        btnClose.setBorderPainted(false);
        btnClose.setOpaque(false);

        btnClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int i;
                for (i = 0; i <= panelArchivos.getTabCount() - 1; i++) {
                    if (title.equals(panelArchivos.getTitleAt(i))) {
                        break;
                    }
                }
                if (JOptionPane.showConfirmDialog(panelArchivos, "DESEA GUARDAR EL ARCHIVO?") == 0) {
                    panelArchivos.removeTabAt(i);
                    String texto = documentos.get(i).ObtenerTexto();
                    File archivo = documentos.get(i).getDocumento();
                    LectorArchivo lector = new LectorArchivo();
                    lector.GuardarTexto(archivo, texto);
                    formatos.remove(i);
                    documentos.remove(i);
                } else {
                    panelArchivos.removeTabAt(i);
                    formatos.remove(i);
                    documentos.remove(i);
                }
            }
        });
        pnlTab.add(lblTitle);
        pnlTab.add(btnClose);
        return pnlTab;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbrir;
    private javax.swing.JMenuItem btnAnalizar;
    private javax.swing.JMenuItem btnAnalizarLista;
    private javax.swing.JButton btnDetener;
    private javax.swing.JMenuItem btnErrores;
    private javax.swing.JMenuItem btnGuardar;
    private javax.swing.JMenuItem btnGuardarComo;
    private javax.swing.JMenuItem btnNuevo;
    private javax.swing.JMenuItem btnNuevoLista;
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnPlay;
    private javax.swing.JMenu btnRep;
    private javax.swing.JMenuItem btnSalir;
    public static javax.swing.JTextArea consola;
    private javax.swing.JTextArea consola2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem limpiarConsola;
    private javax.swing.JTree listaRep;
    private javax.swing.JMenuBar menuBarra;
    private java.awt.Panel panel1;
    private javax.swing.JTabbedPane panelArchivos;
    private javax.swing.JTabbedPane panelArchivos2;
    // End of variables declaration//GEN-END:variables
}
